# Generated by Django 2.2.1 on 2019-05-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
