# Generated by Django 2.2.1 on 2019-05-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_image'),
        ('main', '0004_remove_product_product_owner_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_owner_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
            preserve_default=False,
        ),
    ]
