# Generated by Django 2.2.1 on 2019-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
