# Generated by Django 2.2.1 on 2019-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='Bermet.jpg', upload_to=''),
        ),
    ]
