# Generated by Django 2.2.1 on 2019-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190527_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='Default.jpeg', upload_to=''),
        ),
    ]
